### ISSUE TITLE
這個樣式... 這個排版...

### ISSUE THREAD

**Issue by seadog007** [kiang/drugs#18]
http://drugs.olc.tw/members/login
![2015-01-24 9 05 51](https://cloud.githubusercontent.com/assets/5138409/5887463/e3a79232-a40c-11e4-8e85-f92786e293ac.png)
自己的issue自己解

**Comment by osk2** [comment]
在 f2f5ec1 套上Bootstrap的class，比原本的樣式好一些些 :P

**Comment by seadog007** [comment]
阿靠 我完全忘記有這件事了..............

**Comment by kiang** [comment]
沒關係，我習慣了（攤手） XD

**Comment by kiang** [comment]
resolved at f2f5ec1a5b77d3305d14dad53ac6eb66323fd421
