### ISSUE TITLE
待整合的資料

### ISSUE THREAD

**Issue by pofeng** [kiang/drugs#2]
全部藥品許可證資料集
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=36

藥品健保藥價資料集 : 許可證字號、健保代碼、規格量、規格單位、起期、終期、參考價
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=74

藥品外觀資料集: 許可證字號、中文品名、英文品名、形狀、特殊劑型、顏色、特殊氣味、刻痕、外觀尺寸、標註一、標註二、外觀圖檔連結
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=42

藥品仿單或外盒資料集: 許可證字號、中文品名、英文品名、仿單圖檔連結、外盒圖檔連結
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=39

藥品詳細處分成分資料集
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=43

藥品藥理治療分類ATC碼資料集 ATC Code
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=41

(?) 未註銷藥品許可證資料集 - 未註銷藥品許可證資料
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=37
( 有人建議, 不要列出已註銷的藥物) 

(?) 藥品CCC號列資料集 (中華民國商品標準分類號列)
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=38

原始資料授權
http://data.fda.gov.tw/frontsite/cms/cmsAction.do?method=doClauseDetail&clauseId=1

**Comment by kiang** [comment]
close first, have new issue if new dataset founded
