### ISSUE TITLE
加一個 tagging 功能

### ISSUE THREAD

**Issue by kiang** [kiang/drugs#23]
以 http://www.chinatimes.com/newspapers/20150119000322-260114 為例，可以在宣傳這篇消息時標示相關的藥品資訊

**Comment by kiang** [comment]
新聞提到的成份如下：
Cetirizine
Loratadine
Fexofenadine
Clotrimazole
Miconazole
Triamcinolone
Benzydamine
Omeprazole
Pantoprazole
Azelastine
Triamcinolone
Aspirin
Ketotifen

不過對應的名稱還蠻多元的，像 Cetirizine 就會找到 CETIRIZINE HYDROCHLORIDE 跟 CETIRIZINE DIHYDROCHLORIDE (EQ TO CETIRIZINE 2HCL )

**Comment by Clementtang** [comment]
因為 Cetirizine 這兩種是一樣的東西

**Comment by kiang** [comment]
恩，我沒有能夠識別這樣資訊的能力，等功能開發出來再看有沒有志工幫忙了 ;)

**Comment by t0mst0ne** [comment]
其實只要抓第一個英文字即可 ( 後面接的可以直接省略)

On Wed, Jan 28, 2015 at 12:00 PM, kiang <notifications@github.com> wrote:

> 恩，我沒有能夠識別這樣資訊的能力，等功能開發出來再看有沒有志工幫忙了 ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kiang/drugs/issues/23#issuecomment-71777569>.
>



-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by kiang** [comment]
編輯介面長的像下面這樣，因為成份沒有做歸類，所以個別新聞對應的成份會需要比較繁複的操作，而且很多一樣的成份只是寫法不同（例如有無括弧）...

![screenshot from 2015-01-30 22 28 27](https://cloud.githubusercontent.com/assets/47844/5977082/8d5e2a40-a8cf-11e4-8ac0-fceb69c3564e.png)

**Comment by t0mst0ne** [comment]
應該 OK , 畢竟類似的指示用藥應該慢慢開放, 一次不會增加太多 !

2015-01-30 22:31 GMT+08:00 kiang <notifications@github.com>:

> 編輯介面長的像下面這樣，因為成份沒有做歸類，所以個別新聞對應的成份會需要比較繁複的操作，而且很多一樣的成份只是寫法不同（例如有無括弧）...
>
> [image: screenshot from 2015-01-30 22 28 27]
> <https://cloud.githubusercontent.com/assets/47844/5977082/8d5e2a40-a8cf-11e4-8ac0-fceb69c3564e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kiang/drugs/issues/23#issuecomment-72209285>.
>



-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by kiang** [comment]
雛型已經放入 http://drugs.olc.tw/articles
