### ISSUE TITLE
在搜尋框內按 Enter 毫無作用

### ISSUE THREAD

**Issue by rschiang** [kiang/drugs#25]
按下 Enter 搜尋是 UI 設計上的慣例之一，尤其在大量搜尋清單上的藥名的時候，更能節省不少寶貴的時間。目前的藥要看網站搜尋框按下 Enter 只會重新整理（？），不確定是不是 bug。

**Comment by kiang** [comment]
其實是我偷懶不去處理 XD ，晚點修

**Comment by kiang** [comment]
fixed @ c2621973d72f620662a6d4cba981c8d645088948
