### ISSUE TITLE
單一藥證字號對應多個健保代號

### ISSUE THREAD

**Issue by pofeng** [kiang/drugs#3]
有些外用的藥膏，不同包裝，有不同的健保碼，不同價格，但只有一個藥證字號
所以有些資料被合併了

eg: 衛署藥製字第050128號 
http://drugs.olc.tw/drugs/index/050128

但是健保碼有

A050128309  1kg  2322
A050128316  3g   36.3
A050128335 15g  54
A050128355 100g 477
...
(未完)

**Comment by kiang** [comment]
現有的實作暫時應該可以滿足需求，後續再看看會不會衍生其他問題
