### ISSUE TITLE
已知中西藥藥證字號重複清單

### ISSUE THREAD

**Issue by kiang** [kiang/drugs#30]
"衛署藥製字第004704號","氯芬尼拉明錠"
"衛署藥製004704","川富安神養腦丸"

"衛署藥製字第010801號","易司安栓劑６５公絲"
"衛署藥製010801","”萬國”順乳丸"

"衛署藥製字第016377號","蒙多舒膠囊（蛋白酵素）"
"衛署藥製016377","“勸春堂”白鳳丸（小丸）"

"衛署藥製字第025839號","歐斯卡膠囊１００公絲（異嘌呤醇）"
"衛署藥製025839","“仙豐”訶子粉末"

"衛署藥製字第030162號","西士恩錠"
"衛署藥製030162","“順天堂”治頭瘡一方濃縮散"

"衛署藥製字第030448號","救克明消炎粉（苯磺胺）"
"衛署藥製030448","”仙豐”八珍湯濃縮細粒"

"衛署藥製字第036186號","〝永豐〞舒曼注射液"
"衛署藥製036186","舒曼注射液"

"衛署藥製字第036540號","西華治辛丙二醇"
"衛署藥製036540","”莊松榮”半夏白朮天麻湯濃縮細粒"

"衛署藥製字第041494號","“明德”一路安感冒液"
"衛署藥製041494","“莊松榮”養肝丸濃縮丸"

"衛署藥製字第041495號","感冒膠囊"
"衛署藥製041495","“莊松榮”木賊濃縮細粒"

"衛署藥製字第041496號","""瑞士""拿脂膜衣錠600毫克(健菲布旨)"
"衛署藥製041496","“莊松榮”千斤拔濃縮細粒"

"衛署藥製字第041497號","愛平諾膜衣錠100毫克"
"衛署藥製041497","“莊松榮”款冬花濃縮細粒"

"衛署藥製字第041498號","優良優洛脂錠２０公絲（樂瓦司他汀）"
"衛署藥製041498","”天明”牡蠣濃縮細粒"

"衛署藥製字第041501號","明德華寶洗髮精１０公絲？公克（克康那唑）"
"衛署藥製041501","“天明”鬱金濃縮細粒"

"衛署藥製字第041502號","寶生頭皮屑藥用洗髮精１％（克康那唑）"
"衛署藥製041502","“天明”石斛濃縮細粒"

"衛署藥製字第041503號","咳保寧感冒液"
"衛署藥製041503","“天明”益母草濃縮細粒"

"衛署藥製字第041504號","黴速鎮乳膏１％（克氯黴唑）"
"衛署藥製041504","“信宏”金沸草散濃縮細粒"

"衛署藥製字第042002號","沙利軟膏"
"衛署藥製042002","”順然”豬苓湯濃縮細粒"

"衛署藥製字第042003號","“新喜”倍而珍錠５００公絲（?胼醯胺）"
"衛署藥製042003","”順然”普濟消毒飲濃縮細粒　"

"衛署藥製字第042004號","美寶鈣顆粒"
"衛署藥製042004","”順天堂”龜鹿二仙膠濃縮顆粒"

"衛署藥製字第042005號","維他克勞糖衣錠"
"衛署藥製042005","”莊松榮”當歸飲子濃縮細粒"

"衛署藥製字第042006號","優克膚乳膏"
"衛署藥製042006","”莊松榮”三痹湯濃縮細粒"

"衛署藥製字第042007號","鎮疼能糖衣錠１０公絲（溴化丁基東莨菪僉）"
"衛署藥製042007","”莊松榮”調經丸濃縮細粒"

"衛署藥製字第042008號","克保生糖衣錠"
"衛署藥製042008","”莊松榮”厚朴溫中湯濃縮細粒"

"衛署藥製字第042009號","益命糖衣錠５０公絲（維生素Ｅ）"
"衛署藥製042009","“莊松榮”潤腸湯濃縮細粒"

"衛署藥製字第042010號","滋理治膽糖衣錠１２．５公絲（茴香腦）"
"衛署藥製042010","”莊松榮”一貫煎濃縮細粒"

"衛署藥製字第042011號","“新喜”嗽得安錠１５公絲（氫溴酸石右旋美索芬）"
"衛署藥製042011","”富田”大柴胡湯濃縮錠"

"衛署藥製字第042012號","潰治精糖衣錠２５公絲（每治能）"
"衛署藥製042012","”富田”炙甘草湯濃縮錠"

"衛署藥製字第042013號","""萌髮""康力諾1%抗屑洗髮精"
"衛署藥製042013","“莊松榮”蒼朮濃縮細粒"

"衛署藥製字第042014號","坦適錠５００公絲（碳酸鈣）"
"衛署藥製042014","”德山”養肝丸濃縮丸"

"衛署藥製字第042015號","伊寧洗髮精10毫克/公克"
"衛署藥製042015","”德山”治瘡丸（狐仙封臟丸）"

"衛署藥製字第042016號","平脂樂錠２０公絲（樂瓦司他汀）"
"衛署藥製042016","”德山”福眼明目濃縮散（？菊地黃丸）"

"衛署藥製字第042017號","諾咳複方膠囊"
"衛署藥製042017","”德山”三黃錠（三黃瀉心湯）"

"衛署藥製字第042191號","逸糖錠５公絲（格力匹來）"
"衛署藥製042191","”順然”獨活寄生湯濃縮錠"

"衛署藥製字第044929號","""台灣東洋"" 樂黴素膠囊"
"衛署藥製044929","”天一”木瓜濃縮顆粒"

"衛署藥製字第044930號","""晟德"" 樂黴素懸濁液用顆粒"
"衛署藥製044930","”港香蘭”七寶美髯丹濃縮錠"

"衛署藥製字第049811號","莎芙平注射劑"
"衛署藥製049811","“三才堂”銀翹散濃縮細粒"

"衛署藥製字第050060號","速治解顆粒 400 毫克"
"衛署藥製050060","”正和”柴胡清肝湯濃縮細粒"

"衛署藥製字第052571號","聯豐台中醫用液態氧氣"
"衛署藥製052571","“優之堡”茯神濃縮顆粒"

"衛署成製字第004148號","樂樂鎮痛藥膏布"
"衛署成製004148","""南美""樂樂鎮痛藥膏布"

"衛署成製字第006404號","清喉丸"
"衛署成製006404","""福祿壽三仙""鐵漢青龍丹丸（還少丹）"

"衛署成製字第009838號","櫻桃藥皂"
"衛署成製009838","”生春”清腸丸（加味麻仁丸減味）"

"衛署成製字第015907號","“惠生”浣腸液"
"衛署成製015907","""觀音牌""香砂平胃散（加減味）"

"衛署成製字第015908號","“杏輝”司衛妥藥用漱口液 0.2% (克羅希西定)"
"衛署成製015908","“天良”天良腰骨風濕酸痛外用液"

"衛署成製字第016214號","法樂奇漱口水"
"衛署成製016214","“華陀”斑龍丸"

"衛署成製字第016215號","""華盛頓""口舒０．０５％漱口液（十六烷基氯化口比啶）"
"衛署成製016215","“華陀”杞菊地黃丸"

"衛署成製字第016216號","""久仁""浣腸球液"
"衛署成製016216","“南美”養血壯筋健步丸（加減味）膠囊"

"衛署成製字第016217號","克菌寧酒精液75%"
"衛署成製016217","“三友”紫雲膏"

"衛署成製字第016218號","""天乾""真順浣腸"
"衛署成製016218","“柏諦”歐露癢痛寧膏（白玉膏加減味）"

"衛署成製字第016219號","""萬泰""暢通浣腸液"
"衛署成製016219","“陳建誠虎蜂勇”天王補心丹"

"衛署成製字第016220號","花油精"
"衛署成製016220","“廣信”廣信參仲四物丸"

"衛署成製字第016221號","久明浣腸液"
"衛署成製016221","“浩然堂”雙麟止嗽散（去硃砂）"

"衛署成輸字第000005號","安炎寧口內炎漱劑"
"衛署成輸000005","〝津村〞康蓓芙濃縮顆粒"

"衛部成製字第016636號","克菌寧暢淨漱口水0.12%"
"衛部成製016636","“萬國”斑龍丸"

**Comment by kiang** [comment]
問題已經回報到
http://data.fda.gov.tw/frontsite/data/DataAction.do?method=doDetail&infoId=36

共計 54 個

**Comment by kiang** [comment]
回應時間：2015/03/06 10:58:55

回應內容：敬啟者： 您好，所傳信件，業已收悉。 謝謝告知，本署將盡力防止本署核發的藥品許可證證號與衛生福利部中醫藥司所核發的中藥許可證證號重覆之情事。 感謝您的來信，祝您健康、快樂! 衛生福利部食品藥物管理署 敬復

**Comment by Clementtang** [comment]
剛跟王大人開會，這件事被拿出來講 XD

**Comment by kiang** [comment]
有八卦嗎？ XD

**Comment by Clementtang** [comment]
他好像一直誤解藥要看是你開發出來要營利的軟體... XD 但我也不方便幫你解釋就是了。

**Comment by kiang** [comment]
目前是有營利沒錯啊，有掛廣告，只是大概也只能貼補主機費用吧 :)
