### ISSUE TITLE
藥物健保碼改碼

### ISSUE THREAD

**Issue by t0mst0ne** [kiang/drugs#43]
經過一個 “peace"-like 評鑑之後, 後8碼不變 C變0
BC20174100 = B020174100

要再找一下 reference

**Comment by kiang** [comment]
健保碼與價格改從健保署取得 ref: 2209f47bf35f8b0311dde5d7b829cece32d0c70e

理論上都找的到了，只是舊有的連結就消失了

**Comment by kiang** [comment]
後來實際搜尋時會刻意忽略前面兩碼，藥要看的搜尋是可以部份比對的，第三碼開始接的是藥證編號，這樣就可以避免因為藥廠異動找不到
