### ISSUE TITLE
GLUVIA 健保碼健保價不見

### ISSUE THREAD

**Issue by pofeng** [kiang/drugs#51]
http://drugs.olc.tw/drugs/view/555a264c-1250-4e19-a1fa-148ed38a10d1

GLUVIA 健保碼健保價不見
AC58620100
22.4

**Comment by kiang** [comment]
KC01011272 的配對也失敗，應該是健保碼的計算出問題...

**Comment by kiang** [comment]
在 21c1b21ffb457c5709ea3bb53b1ada4a786a3732 修正了，主要是 衛署xxx 與 衛部xxx 共用健保前置碼導致程式配對錯誤

http://drugs.olc.tw/drugs/index/AC58620100
http://drugs.olc.tw/drugs/index/KC01011272
