### ISSUE TITLE
同一個藥有兩個形狀, 兩組成分 ?

### ISSUE THREAD

**Issue by pofeng** [kiang/drugs#7]
這個藥資料上有兩個形狀 ( 白色圓形平面錠劑 , 黃色三角形凸面錠劑 )
http://drugs.olc.tw/drugs/view/549293e7-bed8-4785-8ed5-1cffd38a10d1

但我記得一直是黃色三角形

**Comment by kiang** [comment]
因為資料移轉的時候沒有保留編號，所以這個連結已經失效，但類似問題可能得往上反應了 :)
