### ISSUE TITLE
也許可以開發個人藥單記錄功能

### ISSUE THREAD

**Issue by kiang** [kiang/drugs#9]
我家那隻今天看醫生拿到了藥單，就心血來潮查了一下，看起來每個項目都可以順利查到：
https://gist.github.com/kiang/47c5175128e8f647154b

這個藥單裡面顆粒狀的都磨成粉了，所以透過系統可以看到它原來長什麼樣子，也會有比醫生講解來的詳細的資訊，所以就想說也許可以開發這樣一個功能，讓使用者自行建立藥單記錄，方便長期追蹤。

然後透過 open data 將這些資訊彙整後公開，提供相關人士研究用。

只是這樣的資訊一方面有隱私疑慮，另一方面也無法斷定使用者是正確輸入，所以累積的資料也許在應用的效果會打了些折扣；變通作法是讓使用者也上傳自己在醫院取得的藥單，只是這就會需要經過比較嚴謹的作業處理，避免個資外洩。

最理想的作法是取得健保系統的資料吧，不過看樣子這個方向門檻高了些

**Comment by wanghaisheng** [comment]
很有意思的项目 ，关注
大陆的话 丁香园和阿里健康的APP都在做类似的功能

**Comment by kiang** [comment]
@pofeng 今天跟一個藥師聊，他說健保用藥記錄只有大醫院才有要求，小診所好像沒有強制規定？

@wanghaisheng 丁香园和阿里健康的APP可以直接查歷史用藥記錄？

**Comment by t0mst0ne** [comment]
應該都有，而且不久就要核刪重覆用藥

kiang <notifications@github.com> 於 2015年1月11日 星期日寫道：

> @pofeng <https://github.com/pofeng>
> 今天跟一個藥師聊，他說健保用藥記錄只有大醫院才有要求，小診所好像沒有強制規定？
>
> @wanghaisheng <https://github.com/wanghaisheng> 丁香园和阿里健康的APP可以直接查歷史用藥記錄？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kiang/drugs/issues/9#issuecomment-69489216>.
>


-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by kiang** [comment]
https://med.nhi.gov.tw/ihke0000/IHKE0100S01.aspx

"請於申請日之隔日8時再至本網頁下載申請結果，本網站依據 台端申請產製資料後保留7日 (例如：104年01月11日提出申請，請於104年01月12日8時至104年01月18日23時59分至本網站下載)"

這種調閱資料庫的系統還要等批次進行，真的是...

**Comment by kiang** [comment]
透過自然人憑證申請取得的資料長這樣：
http://jsfiddle.net/1fnyemr2/

看起來很容易可以匯入與比對，只是申請程序有點繁瑣，而且沒辦法幫其他人申請（有趣的是，小孩要滿 18 歲才可以申請自然人憑證，所以目前無解，先發信去問了）

**Comment by t0mst0ne** [comment]
Pdf ?

kiang <notifications@github.com> 於 2015年1月13日 星期二寫道：

> 透過自然人憑證申請取得的資料長這樣：
> http://jsfiddle.net/1fnyemr2/
>
> 看起來很容易可以匯入與比對，只是申請程序有點繁瑣，而且沒辦法幫其他人申請（有趣的是，小孩要滿 18
> 歲才可以申請自然人憑證，所以目前無解，先發信去問了）
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kiang/drugs/issues/9#issuecomment-69723591>.
>


-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by kiang** [comment]
純網頁格式，就把網頁打包成 zip 檔案後提供下載， zip 檔案有用身份證字號加密

**Comment by t0mst0ne** [comment]
建一個平台提供上傳，付代藥物查詢（仿單etc) ?

感覺越來越像phd

kiang <notifications@github.com> 於 2015年1月13日 星期二寫道：

> 純網頁格式，就把網頁打包成 zip 檔案後提供下載， zip 檔案有用身份證字號加密
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kiang/drugs/issues/9#issuecomment-69724090>.
>


-- 
Linger too long at high altitudes, and your hearing dulls, and your
eyesight dims.   "Facing your Giants" , Max Lucado

**Comment by kiang** [comment]
透過裡面的健保代碼就可以輕易跟藥物連結在一起，所以可以直接做出用藥紀錄。只是裡面的資料侷限在有健保給付的部份，很多藥局其實送了很多額外的藥沒有在紀錄裡，但至少比使用者自行輸入來的有效率多了。

**Comment by kiang** [comment]
回覆如下
1.考量資訊安全及個人資料保護法之規定，目前民眾需持「自然人憑證」進行身分認證後登入系統，惟「自然人憑證」依內政部憑證管理中心所訂申請資格為年滿18歲（含）以上，設籍於本國之國民（即為自然人），且未受監護宣告者，故「全民健保健康存摺」系統目前無法提供18歲以下眷屬或受監護宣告者查詢個人資料.

2. 保險對象如為未滿18歲或未能申請自然人憑證者，需索取特約醫事服務機構向本署申報提供醫療服務之資料，可依「全民健康保險保險人對外提供資料作業要點」填具「全民健康保險保險人提供資料之申請書」（可至 http://www.nhi.gov.tw/resource/bulletin/4443_1020036886A-2.doc 下載或洽本署分區業務組索取），檢附當事人戶口名簿影本或身分證正反面影本（如由代理人申請者，則須加附當事人授權書及代理人身分證明文件正反面影本），繳交工本費300元後，向投保單位所在地之分區業務組提出申請。惟因門、住診申報量過大，每月平均約有3仟萬人次以上，故現可提供自92年1月1日起至申請日前兩個月之就醫日期、醫事機構代碼及名稱、門住診別、業組組別、費用年月、醫事機構地址、醫事機構電話地址等資料，另該資料並非病歷，相關診斷、用藥及就醫或罹病情形，仍應洽相關醫事服務機構之醫師。

---
花 300 塊可以拿到 92 年至今的，只是應該變成紙本吧...

**Comment by kiang** [comment]
初步版本已經上線，可以直接匯入健保局給的壓縮檔案，也可以自行手動建立，畫面則是一個延伸的小功能，計算所有使用到的藥物劑量後排序產生列表呈現。

![screenshot from 2015-03-01 23 13 53](https://cloud.githubusercontent.com/assets/47844/6431372/d7d1471e-c068-11e4-8a6c-3673c68e10b1.png)
